name: integration

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:

jobs:
  lint_test:
    name: Lint & Test
    runs-on: ubuntu-22.04
    # Run on external PRs only as the workflow will be already running for the push event on the branch for internal
    # PRs.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.6.9

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 16

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: pnpm test
