name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Draft new Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
